# description
name: "Title"
description: "Short description"
keywords: "foo, bar, fum, baz, qux, zot"
author: "Leszek Pietrzak"

# address settings
baseurl: "http://boilerplate-jekyll.smutnyleszek.com"
permalink: /post/:title

# site configuration
encoding: utf-8
markdown: kramdown
future: true
safe: true
paginate: 9000
