# description
name: "Title"
description: "Short description"
keywords: "foo, bar, fum, baz, qux, zot"
author: "Leszek Pietrzak"

# address settings
url: "http://boilerplate.smutnyleszek.com"
# url: "http://0.0.0.0:4000"
permalink: /post/:title

# site configuration
encoding: UTF-8
markdown: rdiscount
future: true
paginate: 9000